// React/aprendiendoreact/src/components/Slider.js
import React, { Component } from 'react';

class Slider extends Component {
    render() {
        console.log(this.props)
        return (<div id="slider" className="slider-big">
            <h1>{this.props.title}</h1>
            <a href="blog.html" className="btn-white">{this.props.btn}</a>
        </div>);
    }
}

export default Slider;

// VueJS/aprendiendovue/src/components/Slider.vue
<template>
  <div id="slider" :class="{ 'slider-big': home, 'slider-small': !home }">
    <h1>{{ texto }}</h1>
    <router-link to="/blog" class="btn-white" v-if="home"
      >Ir al blog</router-link
    >
  </div>
</template>

<script>
export default {
  name: "Slider",
  props: ["texto", "home"],
};
</script>
