// VueJS/aprendiendovue/src/components/Pelicula.vue
<template>
  <div>
    <article class="article-item">
      <div class="image-wrap">
        <img
          :src="pelicula.image"
          :alt="pelicula.title"
          :title="pelicula.title"
        />
      </div>

      <h2>{{ pelicula.title }}</h2>
      <span
        class="date"
        v-bind:class="{
          yeargreen: pelicula.year >= 2015,
          yearred: pelicula.year < 2015,
        }"
      >
        {{ pelicula.year }}
      </span>
      <a href="#">Leer más</a>
      <input
        type="button"
        value="Marcar como favorita"
        @click="pasarFavoritaAlPadre(pelicula)"
      />
      <div class="clearfix"></div>
    </article>
  </div>
</template>

<script>
export default {
  name: 'Pelicula',
  props: ['pelicula'],
  methods: {
    pasarFavoritaAlPadre(pelicula) {
      alert("Botón pulsado");
      console.log(pelicula);
      this.$emit('favorita', pelicula);
    },
  },
};
</script>

// React/aprendiendoreact/src/components/Pelicula.js
import React, { Component } from 'react';

class Pelicula extends Component {

    marcar = () => {
        this.props.marcarFavorita(this.props.marcarFavorita(this.pelicula), this.props.indice);
    }

    favorita = (pelicula, indice) => {
        console.log(pelicula, indice);
        this.setState({
            favorita: pelicula
        });
    }
    render() {
        const pelicula = this.props.pelicula;
        const { titulo, image } = pelicula;
        return (
            < article className="article-item" id="article-template" >
                <div className="image-wrap">
                    <img src={image} alt={titulo} />
                </div>

                <h2>{titulo}</h2>
                <span className="date">
                    Hace 5 minutos
                </span>
                <a href="#">Leer más</a>
                <button onClick={this.marcar}>Marca como favorita</button>
                <div className="clearfix"></div>
            </article>
        );
    }
}

export default Pelicula;
