// Angular/AprendiendoAngular/src/app/components/pelicula/pelicula.component.ts
import { Component, Input,Output, OnInit, EventEmitter} from '@angular/core';
import { Pelicula } from 'src/app/models/pelicula';

@Component({
  selector: 'app-pelicula',
  templateUrl: './pelicula.component.html',
  styleUrls: ['./pelicula.component.css']
})
export class PeliculaComponent implements OnInit {

  @Input()
  pelicula!: Pelicula;
  @Output() MarcarFavorita = new EventEmitter();
  constructor() { }

  ngOnInit(): void {
  }

  seleccionar(event: any, pelicula: any){
   this.MarcarFavorita.emit({
     pelicula:pelicula
   })
  }
}

<article class="article-item" >
    <div class="image-wrap">
        <img src="{{pelicula.image}}" alt="{{pelicula.title}}">
    </div>

    <h2>{{pelicula.title}}</h2>
    <span class="date">
        Hace 5 minutos
    </span>
    <span class="year" 
        [ngClass]="{'year-green': pelicula.year > 2016,
        'year-red': pelicula.year < 2016}">
        {{pelicula.year}}
    </span>
    <a href="#">Leer más</a>
<div class="clearfix"></div>
</article>

<button (click)="seleccionar($event, pelicula)">Seleccionar como Favorita</button>

// React/aprendiendoreact/src/components/Pelicula.js
import React, { Component } from 'react';

class Pelicula extends Component {

    marcar = () => {
        this.props.marcarFavorita(this.props.marcarFavorita(this.pelicula), this.props.indice);
    }

    favorita = (pelicula, indice) => {
        console.log(pelicula, indice);
        this.setState({
            favorita: pelicula
        });
    }
    render() {
        const pelicula = this.props.pelicula;
        const { titulo, image } = pelicula;
        return (
            < article className="article-item" id="article-template" >
                <div className="image-wrap">
                    <img src={image} alt={titulo} />
                </div>

                <h2>{titulo}</h2>
                <span className="date">
                    Hace 5 minutos
                </span>
                <a href="#">Leer más</a>
                <button onClick={this.marcar}>Marca como favorita</button>
                <div className="clearfix"></div>
            </article>
        );
    }
}

export default Pelicula;
