// VueJS/aprendiendovue/src/components/Sidebar.vue
<template>
  <aside id="sidebar">
    <div id="nav-blog" class="sidebar-item">
      <h3>Puedes hacer esto</h3>
      <a href="#" class="btn btn-success">Crear Articulo</a>
    </div>

    <div id="search" class="sidebar-item">
      <h3>Buscador</h3>
      <p href="#">Encuentra el artículo que buscas</p>
      <form action="">
        <input type="text" name="search" />
        <input type="submit" name="submit" value="buscar" class="btn" />
      </form>
    </div>
  </aside>
</template>

<script>
export default {
  name: "Sidebar",
};
</script>

// React/aprendiendoreact/src/components/Sidebar.js
import React, { Component } from 'react';

class Sidebar extends Component {
    render() {
        return (
            <aside id="sidebar">
                <div id="nav-blog" className="sidebar-item">
                    <h3>Puedes hacer esto</h3>
                    <a href="#" className="btn btn-success">Crear Articulo</a>
                </div>

                <div id="search" className="sidebar-item">
                    <h3>Buscador</h3>
                    <p href="#">Encuentra el artículo que buscas</p>
                    <form action="">
                        <input type="text" name="search" />
                        <input type="submit" name="submit" value="buscar" className="btn" />
                    </form>
                </div>
            </aside>
        );
    }
}

export default Sidebar;
