// React/aprendiendoreact/src/components/Slider.js
import React, { Component } from 'react';

class Slider extends Component {
    render() {
        console.log(this.props)
        return (<div id="slider" className="slider-big">
            <h1>{this.props.title}</h1>
            <a href="blog.html" className="btn-white">{this.props.btn}</a>
        </div>);
    }
}

export default Slider;

// Angular/AprendiendoAngular/src/app/components/slider/slider.component.ts
import { Component, Input, OnInit } from '@angular/core';


@Component({
  selector: 'app-slider',
  templateUrl: './slider.component.html',
  styleUrls: ['./slider.component.css']
})
export class SliderComponent implements OnInit {

  @Input() nombre = '';
  @Input() size = '';
  constructor() { 
  }

  ngOnInit(): void {
  }

}

<div id="slider" [ngClass]="{'slider-big':size || size == 'big', 'slider-small': size == 'small'}">
    <h1>{{nombre}}</h1>
    <a href="blog.html" class="btn-white">Ir al blog</a>
</div>
